// test_codecs.c - T-040: the golden vectors of tests/data/audio/ (generated by
// tools/gen_audio_vectors.py), the broken files of tests/data/, and a fuzz pass
// on the headers.
//
// The reference is the formula, not a file: every vector holds the same 1 kHz
// sine at -6 dBFS, so a decode is checked against sin() to within one quantum
// of its own depth. Bit-exactness is only ever asserted *between* our decoders
// - FLAC and AIFF against WAV - because that is the actual claim ("lossless"),
// and it does not depend on two sin() implementations agreeing to the last bit.
//
// Lossy formats are scored by fitting a sine of the right frequency to the
// decoded block by least squares and measuring what is left. That is immune to
// the encoder delay every MP3 and AAC file carries, which a sample by sample
// comparison is not.

#include <math.h>

#define TEST_AUDIO_DIR "tests\\data\\audio\\"
#define TEST_CODEC_RATE 44100.0
#define TEST_CODEC_TONE 1000.0
#define TEST_CODEC_AMPLITUDE 0.5011872336272722  // -6 dBFS
#define TEST_CODEC_LONG_FRAMES 22050
#define TEST_CODEC_SHORT_FRAMES 4410
#define TEST_CODEC_LOSSY_FRAMES 44100  // 1 s : les vecteurs MP3/OGG/M4A
#define TEST_CODEC_FUZZ 200

static f64 test_codec_sine(u64 index, f64 hz) {
    return TEST_CODEC_AMPLITUDE *
           sin(2.0 * 3.14159265358979323846 * hz / TEST_CODEC_RATE * (f64)index);
}

typedef struct TestPcm {
    f32 *channel[CODEC_MAX_CHANNELS];
    u64 frames;
    u32 channels;
    u32 sample_rate;
    u64 total_frames;  // what the container claimed
} TestPcm;

// Decodes a whole file into the arena, one CODEC_BLOCK_FRAMES block at a time,
// exactly the way the pipeline of T-041 will.
static CodecStatus test_codec_decode(Arena *arena, const char *name, TestPcm *out) {
    StructZero(out);
    String8 path = str8f(arena, "%s%s", TEST_AUDIO_DIR, name);
    Decoder *decoder = 0;
    CodecStatus status = codec_open(&decoder, path);
    if (status != CODEC_OK) { return status; }

    out->channels = decoder->info.channels;
    out->sample_rate = decoder->info.sample_rate;
    out->total_frames = decoder->info.total_frames;
    u64 capacity = decoder->info.total_frames ? decoder->info.total_frames + CODEC_BLOCK_FRAMES
                                              : (u64)(TEST_CODEC_RATE * 4);
    f32 *block[CODEC_MAX_CHANNELS];
    for (u32 c = 0; c < out->channels; c += 1) {
        out->channel[c] = push_array(arena, f32, capacity);
        block[c] = push_array(arena, f32, CODEC_BLOCK_FRAMES);
    }
    for (;;) {
        u32 got = codec_read_f32_planar(decoder, block, CODEC_BLOCK_FRAMES);
        if (got == 0 || out->frames + got > capacity) { break; }
        for (u32 c = 0; c < out->channels; c += 1) {
            mem_copy(out->channel[c] + out->frames, block[c], got * sizeof(f32));
        }
        out->frames += got;
    }
    codec_close(decoder);
    return CODEC_OK;
}

// Signal to noise against the best fitting sine of frequency `hz`: the encoder
// delay and any gain the codec applied fall out of the fit.
static f64 test_codec_snr_db(const f32 *samples, u64 first, u64 count, f64 hz) {
    f64 omega = 2.0 * 3.14159265358979323846 * hz / TEST_CODEC_RATE;
    f64 sum_ss = 0, sum_cc = 0, sum_xs = 0, sum_xc = 0;
    for (u64 i = 0; i < count; i += 1) {
        f64 phase = omega * (f64)(first + i);
        f64 s = sin(phase);
        f64 c = cos(phase);
        f64 x = samples[first + i];
        sum_ss += s * s;
        sum_cc += c * c;
        sum_xs += x * s;
        sum_xc += x * c;
    }
    f64 a = (sum_ss > 0.0) ? sum_xs / sum_ss : 0.0;
    f64 b = (sum_cc > 0.0) ? sum_xc / sum_cc : 0.0;
    f64 signal = 0, noise = 0;
    for (u64 i = 0; i < count; i += 1) {
        f64 phase = omega * (f64)(first + i);
        f64 fit = a * sin(phase) + b * cos(phase);
        f64 error = (f64)samples[first + i] - fit;
        signal += fit * fit;
        noise += error * error;
    }
    if (noise <= 0.0) { return 999.0; }
    return 10.0 * log10(signal / noise);
}

static f64 test_codec_max_error(const TestPcm *pcm, u64 count, f64 hz) {
    f64 worst = 0.0;
    for (u64 i = 0; i < count && i < pcm->frames; i += 1) {
        f64 error = (f64)pcm->channel[0][i] - test_codec_sine(i, hz);
        if (error < 0.0) { error = -error; }
        if (error > worst) { worst = error; }
    }
    return worst;
}

static b32 test_codec_identical(const TestPcm *a, const TestPcm *b) {
    if (a->frames != b->frames || a->channels != b->channels) { return 0; }
    for (u32 c = 0; c < a->channels; c += 1) {
        for (u64 i = 0; i < a->frames; i += 1) {
            if (a->channel[c][i] != b->channel[c][i]) { return 0; }
        }
    }
    return 1;
}

static b32 test_codec_have(Arena *arena, const char *name) {
    ArenaTemp scratch = arena_temp_begin(arena);
    String8 path = str8f(arena, "%s%s", TEST_AUDIO_DIR, name);
    OsFileInfo info;
    b32 exists = os_file_stat(path, &info) && info.size > 0;
    arena_temp_end(scratch);
    return exists;
}

// --- signatures ------------------------------------------------------------

TEST(codec_probe_by_signature) {
    struct {
        const char *dir;
        const char *name;
        CodecId id;
    } cases[] = {
        {TEST_AUDIO_DIR, "sine_16.wav", CODEC_WAV},
        {TEST_AUDIO_DIR, "sine_16.aif", CODEC_AIFF},
        {TEST_AUDIO_DIR, "sine_sowt.aifc", CODEC_AIFF},
        {TEST_AUDIO_DIR, "sine.flac", CODEC_FLAC},
        {TEST_AUDIO_DIR, "sine.mp3", CODEC_MP3},
        {TEST_AUDIO_DIR, "sine.ogg", CODEC_OGG_VORBIS},
        {TEST_AUDIO_DIR, "sine.m4a", CODEC_MP4},
        {"tests\\data\\", "opus.opus", CODEC_OPUS},
        {"tests\\data\\", "id3v23_utf16.mp3", CODEC_MP3},
        {"tests\\data\\", "cover_256.png", CODEC_NONE},
    };
    for (u64 i = 0; i < ArrayCount(cases); i += 1) {
        String8 path = str8f(arena, "%s%s", cases[i].dir, cases[i].name);
        String8 bytes = os_file_read_all(arena, path);
        if (!bytes.size) { continue; }  // a vector the generator could not make
        CodecId probed = codec_probe_bytes(str8_prefix(bytes, 512));
        if (probed != cases[i].id) { test_report("  %s -> %d\n", cases[i].name, (i32)probed); }
        EXPECT(probed == cases[i].id);
    }
}

TEST(codec_refuses_what_it_cannot_decode) {
    Decoder *decoder = 0;
    EXPECT(codec_open(&decoder, str8_lit("tests\\data\\opus.opus")) == CODEC_ERR_UNSUPPORTED);
    EXPECT(codec_open(&decoder, str8_lit("tests\\data\\cover_256.png")) == CODEC_ERR_FORMAT);
    EXPECT(codec_open(&decoder, str8_lit("tests\\data\\does_not_exist.mp3")) == CODEC_ERR_FILE);
    EXPECT(codec_open(&decoder, str8_lit("tests\\data\\empty.mp3")) == CODEC_ERR_FILE);
}

// --- WAV -------------------------------------------------------------------

TEST(codec_wav_pcm_and_float) {
    struct {
        const char *name;
        u64 frames;
        f64 tolerance;  // one quantum of the file's own depth
    } cases[] = {
        {"sine_16.wav", TEST_CODEC_LONG_FRAMES, 1.0 / 32768.0},
        {"sine_8.wav", TEST_CODEC_SHORT_FRAMES, 3.0 / 256.0},
        {"sine_24.wav", TEST_CODEC_SHORT_FRAMES, 1.0 / 8388608.0},
        {"sine_32.wav", TEST_CODEC_SHORT_FRAMES, 1.0 / 8388608.0},
        {"sine_f32.wav", TEST_CODEC_SHORT_FRAMES, 1.0 / 8388608.0},
    };
    for (u64 i = 0; i < ArrayCount(cases); i += 1) {
        TestPcm pcm;
        EXPECT(test_codec_decode(arena, cases[i].name, &pcm) == CODEC_OK);
        EXPECT(pcm.sample_rate == 44100);
        EXPECT(pcm.channels == 1);
        EXPECT(pcm.total_frames == cases[i].frames);
        EXPECT(pcm.frames == cases[i].frames);
        f64 worst = test_codec_max_error(&pcm, pcm.frames, TEST_CODEC_TONE);
        if (worst > cases[i].tolerance) {
            test_report("  %s: erreur max %d ulp\n", cases[i].name, (i32)(worst * 8388608.0));
        }
        EXPECT(worst <= cases[i].tolerance);
    }
}

TEST(codec_wav_stereo_is_deinterleaved) {
    TestPcm pcm;
    EXPECT(test_codec_decode(arena, "sine_stereo_16.wav", &pcm) == CODEC_OK);
    EXPECT(pcm.channels == 2);
    EXPECT(pcm.frames == TEST_CODEC_SHORT_FRAMES);
    // Left is the 1 kHz tone, right is 2 kHz: a channel swap or an interleaving
    // bug shows up as a fit that fails on one of the two.
    EXPECT(test_codec_snr_db(pcm.channel[0], 0, pcm.frames, TEST_CODEC_TONE) > 80.0);
    EXPECT(test_codec_snr_db(pcm.channel[1], 0, pcm.frames, 2.0 * TEST_CODEC_TONE) > 80.0);
    EXPECT(test_codec_snr_db(pcm.channel[1], 0, pcm.frames, TEST_CODEC_TONE) < 10.0);
}

// --- AIFF ------------------------------------------------------------------

TEST(codec_aiff_big_endian_and_aifc) {
    TestPcm wav;
    TestPcm aiff;
    EXPECT(test_codec_decode(arena, "sine_16.wav", &wav) == CODEC_OK);
    EXPECT(test_codec_decode(arena, "sine_16.aif", &aiff) == CODEC_OK);
    EXPECT(aiff.sample_rate == 44100);  // the 80 bit extended rate of COMM
    EXPECT(aiff.frames == TEST_CODEC_LONG_FRAMES);
    EXPECT(test_codec_identical(&wav, &aiff));  // same samples, other byte order

    TestPcm sowt;
    EXPECT(test_codec_decode(arena, "sine_sowt.aifc", &sowt) == CODEC_OK);
    EXPECT(sowt.frames == TEST_CODEC_SHORT_FRAMES);
    EXPECT(test_codec_max_error(&sowt, sowt.frames, TEST_CODEC_TONE) <= 1.0 / 32768.0);

    TestPcm floats;
    EXPECT(test_codec_decode(arena, "sine_f32.aifc", &floats) == CODEC_OK);
    EXPECT(floats.frames == TEST_CODEC_SHORT_FRAMES);
    EXPECT(test_codec_max_error(&floats, floats.frames, TEST_CODEC_TONE) <= 1.0 / 8388608.0);
}

// --- FLAC ------------------------------------------------------------------

TEST(codec_flac_is_lossless) {
    TestPcm wav;
    TestPcm flac;
    EXPECT(test_codec_decode(arena, "sine_16.wav", &wav) == CODEC_OK);
    EXPECT(test_codec_decode(arena, "sine.flac", &flac) == CODEC_OK);
    EXPECT(flac.sample_rate == 44100);
    EXPECT(flac.channels == 1);
    EXPECT(flac.total_frames == TEST_CODEC_LONG_FRAMES);
    EXPECT(flac.frames == TEST_CODEC_LONG_FRAMES);
    EXPECT(test_codec_identical(&wav, &flac));
}

// --- lossy -----------------------------------------------------------------

TEST(codec_mp3_ogg_m4a_snr) {
    const char *names[] = {"sine.mp3", "sine.ogg", "sine.m4a"};
    // The floors are the *encoders*' quality, not ours. This machine has no
    // ffmpeg, so the vectors come out of VLC, whose Vorbis and AAC encoders sit
    // far below LAME on a pure tone (measured: 74 / 53 / 28 dB, and VLC's own
    // decoder agrees with ours to within 0.4 dB on all three). Regenerating the
    // vectors where ffmpeg exists lifts all three above 60 dB - see the
    // Livraison of T-040.
    f64 floors[] = {60.0, 45.0, 20.0};
    for (u64 i = 0; i < ArrayCount(names); i += 1) {
        if (!test_codec_have(arena, names[i])) {
            test_report("  skip %s (vecteur absent)\n", names[i]);
            continue;
        }
        TestPcm pcm;
        EXPECT(test_codec_decode(arena, names[i], &pcm) == CODEC_OK);
        EXPECT(pcm.sample_rate == 44100);
        // The container's own duration is the reference here: a lossy encoder
        // trims and pads as it likes, but a decoder that stops early or runs on
        // disagrees with what the file says about itself.
        EXPECT(pcm.frames + 2048 > pcm.total_frames && pcm.frames <= pcm.total_frames + 2048);
        EXPECT(pcm.frames > TEST_CODEC_LOSSY_FRAMES - 6000);
        EXPECT(pcm.frames < TEST_CODEC_LOSSY_FRAMES + 6000);
        f64 snr = test_codec_snr_db(pcm.channel[0], 6000, 30000, TEST_CODEC_TONE);
        test_report("  %s: %llu frames, SNR %d dB\n", names[i], pcm.frames, (i32)snr);
        EXPECT(snr > floors[i]);
    }
}

// --- seek, end of stream ---------------------------------------------------

// Reads `count` frames at `frame` and checks they are the same frames a full
// decode put there. Exactness is the point: everything downstream of T-040
// (loudness gating, trimming) indexes into the stream by frame.
static b32 test_codec_seek_matches(Arena *arena, const char *name, u64 frame, u32 count) {
    ArenaTemp temp = arena_temp_begin(arena);
    TestPcm whole;
    b32 ok = test_codec_decode(arena, name, &whole) == CODEC_OK && whole.frames >= frame + count;
    if (ok) {
        String8 path = str8f(arena, "%s%s", TEST_AUDIO_DIR, name);
        Decoder *decoder = 0;
        ok = codec_open(&decoder, path) == CODEC_OK;
        if (ok) {
            f32 *block[CODEC_MAX_CHANNELS];
            for (u32 c = 0; c < decoder->info.channels; c += 1) {
                block[c] = push_array(arena, f32, CODEC_BLOCK_FRAMES);
            }
            ok = codec_seek(decoder, frame) &&
                 codec_read_f32_planar(decoder, block, count) == count;
            for (u32 i = 0; ok && i < count; i += 1) {
                ok = block[0][i] == whole.channel[0][frame + i];
            }
            codec_close(decoder);
        }
    }
    arena_temp_end(temp);
    return ok;
}

TEST(codec_seek_is_exact) {
    EXPECT(test_codec_seek_matches(arena, "sine_16.wav", 10000, 512));
    EXPECT(test_codec_seek_matches(arena, "sine_16.aif", 10000, 512));
    EXPECT(test_codec_seek_matches(arena, "sine.flac", 10000, 512));
    if (test_codec_have(arena, "sine.mp3")) {
        EXPECT(test_codec_seek_matches(arena, "sine.mp3", 8000, 512));
    }
    if (test_codec_have(arena, "sine.ogg")) {
        EXPECT(test_codec_seek_matches(arena, "sine.ogg", 8000, 512));
    }
}

TEST(codec_end_of_stream) {
    Decoder *decoder = 0;
    EXPECT(codec_open(&decoder, str8_lit(TEST_AUDIO_DIR "sine_16.wav")) == CODEC_OK);
    f32 *block[1];
    block[0] = push_array(arena, f32, CODEC_BLOCK_FRAMES);
    u64 total = 0;
    for (;;) {
        u32 got = codec_read_f32_planar(decoder, block, CODEC_BLOCK_FRAMES);
        if (!got) { break; }
        total += got;
    }
    EXPECT(total == TEST_CODEC_LONG_FRAMES);
    // Past the end it stays at 0 rather than restarting or faulting.
    EXPECT(codec_read_f32_planar(decoder, block, CODEC_BLOCK_FRAMES) == 0);
    EXPECT(codec_read_f32_planar(decoder, block, CODEC_BLOCK_FRAMES) == 0);
    // And a seek back makes it readable again.
    EXPECT(codec_seek(decoder, 0));
    EXPECT(codec_read_f32_planar(decoder, block, 256) == 256);
    codec_close(decoder);
}

// --- malformed input -------------------------------------------------------

TEST(codec_broken_files_fail_cleanly) {
    const char *names[] = {
        "broken_flac.flac",    "broken_wav.wav", "broken_ogg.ogg",        "broken_truncated.mp3",
        "broken_mp4.m4a",      "broken_ape.mp3", "broken_frame_size.mp3", "broken_huge_size.mp3",
        "broken_mp4_loop.m4a", "tiny.mp3",       "aiff.aif",              "wav.wav",
    };
    f32 *block[CODEC_MAX_CHANNELS];
    for (u32 c = 0; c < CODEC_MAX_CHANNELS; c += 1) {
        block[c] = push_array(arena, f32, CODEC_BLOCK_FRAMES);
    }
    for (u64 i = 0; i < ArrayCount(names); i += 1) {
        String8 path = str8f(arena, "tests\\data\\%s", names[i]);
        Decoder *decoder = 0;
        CodecStatus status = codec_open(&decoder, path);
        // Either it refuses the file, or it opens and decodes what is there
        // without ever running off the end: both are a clean outcome.
        EXPECT(status != CODEC_OK || decoder->info.sample_rate != 0);
        if (status != CODEC_OK) { continue; }
        for (u32 block_index = 0; block_index < 64; block_index += 1) {
            if (codec_read_f32_planar(decoder, block, CODEC_BLOCK_FRAMES) == 0) { break; }
        }
        codec_close(decoder);
    }
}

// The headers are where a decoder trusts a length it has not checked, so that
// is where the mutations go. Under the ASan test build a single byte read past
// a buffer stops the run.
TEST(codec_header_fuzz) {
    const char *names[] = {
        "sine_16.wav",  "sine_8.wav",    "sine_24.wav", "sine_f32.wav", "sine_stereo_16.wav",
        "sine_16.aif",  "sine_sowt.aifc", "sine_f32.aifc", "sine.flac",  "sine.mp3",
        "sine.ogg",
    };
    String8 temp_dir = os_known_folder(arena, OsKnownFolder_Temp);
    EXPECT(temp_dir.size != 0);
    String8 temp_path = os_path_join(arena, temp_dir, str8_lit("minidisk_codec_fuzz.bin"));
    f32 *block[CODEC_MAX_CHANNELS];
    for (u32 c = 0; c < CODEC_MAX_CHANNELS; c += 1) {
        block[c] = push_array(arena, f32, CODEC_BLOCK_FRAMES);
    }

    u64 seed = 0x9E3779B97F4A7C15ull;
    u64 opened = 0;
    for (u64 v = 0; v < ArrayCount(names); v += 1) {
        if (!test_codec_have(arena, names[v])) { continue; }
        ArenaTemp scratch = arena_temp_begin(arena);
        String8 source = os_file_read_all(arena, str8f(arena, "%s%s", TEST_AUDIO_DIR, names[v]));
        u8 *copy = push_array(arena, u8, source.size);
        u64 header = (source.size < KB(4)) ? source.size : KB(4);
        for (u64 i = 0; i < TEST_CODEC_FUZZ; i += 1) {
            mem_copy(copy, source.str, source.size);
            u64 mutations = 1 + (hash64_mix(seed++) % 4);
            for (u64 m = 0; m < mutations; m += 1) {
                copy[hash64_mix(seed++) % header] = (u8)(hash64_mix(seed++) & 0xFF);
            }
            if (!os_file_write_all(temp_path, str8(copy, source.size))) {
                test_report("  fuzz: ecriture impossible dans %S\n", temp_path);
                break;
            }
            Decoder *decoder = 0;
            if (codec_open(&decoder, temp_path) != CODEC_OK) { continue; }
            opened += 1;
            for (u32 b = 0; b < 8; b += 1) {
                if (codec_read_f32_planar(decoder, block, CODEC_BLOCK_FRAMES) == 0) { break; }
            }
            codec_seek(decoder, 1000);
            codec_read_f32_planar(decoder, block, CODEC_BLOCK_FRAMES);
            codec_close(decoder);
        }
        arena_temp_end(scratch);
    }
    os_file_delete(temp_path);
    test_report("  fuzz: %llu ouvertures sur %llu mutations\n", opened,
                (u64)ArrayCount(names) * TEST_CODEC_FUZZ);
    // A fuzz where nothing opens tests nothing: most mutations land past the
    // magic bytes and must still reach the decoders.
    EXPECT(opened > ArrayCount(names) * TEST_CODEC_FUZZ / 4);
}

static void test_codecs_run_all(void) {
    test_report("codecs\n");
    RUN(codec_probe_by_signature);
    RUN(codec_refuses_what_it_cannot_decode);
    RUN(codec_wav_pcm_and_float);
    RUN(codec_wav_stereo_is_deinterleaved);
    RUN(codec_aiff_big_endian_and_aifc);
    RUN(codec_flac_is_lossless);
    RUN(codec_mp3_ogg_m4a_snr);
    RUN(codec_seek_is_exact);
    RUN(codec_end_of_stream);
    RUN(codec_broken_files_fail_cleanly);
    RUN(codec_header_fuzz);
}
