// test_tags.c - T-011: the golden vectors of tests/data/ (generated by
// tools/gen_tag_vectors.py), the broken variants that must fail cleanly, and a
// fuzz pass of 10 000 mutations per vector under ASan.
//
// Expected values are written out in full rather than computed: a test that
// recomputes the parser's arithmetic proves nothing.

#define TEST_TAGS_DIR "tests\\data\\"

typedef struct TestTagFile {
    String8 path;
    String8 bytes;
} TestTagFile;

static TestTagFile test_tags_load(Arena *arena, const char *name) {
    TestTagFile file;
    file.path = str8f(arena, "%s%s", TEST_TAGS_DIR, name);
    file.bytes = os_file_read_all(arena, file.path);
    return file;
}

// The real path a scan takes: open, head, tail, parse, fall back on the name.
static b32 test_tags_read(Arena *arena, Tags *tags, const char *name) {
    TestTagFile file = test_tags_load(arena, name);
    u8 *head = push_array(arena, u8, TAGS_BLOCK_SIZE);
    u8 *tail = push_array(arena, u8, TAGS_BLOCK_SIZE);
    String8 path = str8f(arena, "%s%s", TEST_TAGS_DIR, name);
    OsFileInfo info;
    u64 size = os_file_stat(path, &info) ? info.size : 0;
    return tags_read_file(tags, path, size, head, tail);
}

#define EXPECT_STR(field, literal) EXPECT(str8_eq((field), str8_lit(literal)))

TEST(tags_id3v23_utf16) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "id3v23_utf16.mp3"));
    EXPECT_STR(tags.title, "Sur le fil");
    EXPECT_STR(tags.artist, "Yann Tiersen");
    EXPECT_STR(tags.album, "Le Fabuleux Destin");
    EXPECT_STR(tags.album_artist, "Yann Tiersen");
    EXPECT_STR(tags.genre, "Soundtrack");
    EXPECT(tags.track_no == 7);
    EXPECT(tags.disc_no == 1);
    EXPECT(tags.year == 2001);
    EXPECT(tags.codec == LibCodec_MP3);
    EXPECT(tags.sample_rate == 44100);
    EXPECT(tags.channels == 2);
    EXPECT(tags.duration_ms == 78367);              // 3000 Xing frames at 44100 Hz
    EXPECT(tags.replaygain_track_db == -1856);      // -7.25 dB in 1/256 dB
    EXPECT(tags.cover_size == 512);
    EXPECT(tags.cover_hash != 0);
    EXPECT(tags.cover_offset > 10 && tags.cover_offset + 512 <= 2914);
}

TEST(tags_id3v24_unsync_utf8) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "id3v24_unsync.mp3"));
    EXPECT_STR(tags.title, "Caf\xC3\xA9" " M\xC3\xBC" "ller");
    EXPECT_STR(tags.artist, "Ensemble \xC3\x89" "ole");
    EXPECT_STR(tags.album, "Nuit blanche");
    EXPECT_STR(tags.genre, "Rock");                 // "(17)" through the v1 table
    EXPECT(tags.track_no == 3);
    EXPECT(tags.year == 2019);                      // TDRC "2019-04-01"
    EXPECT(tags.duration_ms == 39183);
}

TEST(tags_id3v22) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "id3v22.mp3"));
    EXPECT_STR(tags.title, "Petite chanson");
    EXPECT_STR(tags.artist, "Les Anciens");
    EXPECT_STR(tags.album, "Demos");
    EXPECT(tags.track_no == 2);
    EXPECT(tags.duration_ms == 23510);
}

TEST(tags_id3v1_and_cbr) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "id3v1_only.mp3"));
    EXPECT_STR(tags.title, "Sonate");
    EXPECT_STR(tags.artist, "Trio Nocturne");
    EXPECT_STR(tags.album, "Recital");
    EXPECT_STR(tags.genre, "Classical");
    EXPECT(tags.year == 1998);
    EXPECT(tags.track_no == 5);                     // v1.1 steals the comment's tail
    EXPECT(tags.duration_ms == 521);                // no Xing: 8340 bytes at 128 kbit/s
}

TEST(tags_mpeg_vbri) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "mpeg_vbri.mp3"));
    EXPECT(tags.duration_ms == 52244);
    EXPECT(tags.sample_rate == 44100);
    // No tag at all: the fallbacks are the file name and its two parent folders.
    EXPECT_STR(tags.title, "mpeg_vbri");
    EXPECT_STR(tags.album, "data");
    EXPECT_STR(tags.artist, "tests");
}

TEST(tags_ape_tail) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "ape_tail.mp3"));
    EXPECT_STR(tags.title, "Marche");
    EXPECT_STR(tags.artist, "Fanfare du Nord");
    EXPECT_STR(tags.album, "Places");
    EXPECT_STR(tags.album_artist, "Fanfare du Nord");
    EXPECT_STR(tags.genre, "Brass");
    EXPECT(tags.track_no == 4);
    EXPECT(tags.disc_no == 1);
    EXPECT(tags.year == 2008);
    EXPECT(tags.replaygain_track_db == 640);        // +2.50 dB
    EXPECT(tags.duration_ms == 521);                // the APE bytes are not audio
}

TEST(tags_flac) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "flac.flac"));
    EXPECT_STR(tags.title, "Nuages");
    EXPECT_STR(tags.artist, "Django");
    EXPECT_STR(tags.album, "Swing 39");
    EXPECT_STR(tags.album_artist, "Quintette");
    EXPECT_STR(tags.genre, "Jazz");
    EXPECT(tags.track_no == 5);
    EXPECT(tags.disc_no == 1);
    EXPECT(tags.year == 1940);
    EXPECT(tags.codec == LibCodec_FLAC);
    EXPECT(tags.sample_rate == 44100);
    EXPECT(tags.channels == 2);
    EXPECT(tags.duration_ms == 3500);               // 154 350 samples
    EXPECT(tags.replaygain_track_db == -793);       // -3.10 dB
    EXPECT(tags.cover_size == 512 && tags.cover_hash != 0);
}

TEST(tags_ogg_vorbis) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "ogg_vorbis.ogg"));
    EXPECT_STR(tags.title, "Vent d'ouest");
    EXPECT_STR(tags.artist, "Mar\xC3\xA9" "e");
    EXPECT_STR(tags.album, "Littoral");
    EXPECT_STR(tags.genre, "Ambient");
    EXPECT(tags.track_no == 2);
    EXPECT(tags.year == 2015);
    EXPECT(tags.codec == LibCodec_OGG);
    EXPECT(tags.sample_rate == 44100);
    EXPECT(tags.channels == 2);
    EXPECT(tags.duration_ms == 4000);               // last granule / rate
}

TEST(tags_opus) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "opus.opus"));
    EXPECT_STR(tags.title, "Ligne claire");
    EXPECT_STR(tags.artist, "Atelier 12");
    EXPECT(tags.codec == LibCodec_OPUS);
    EXPECT(tags.sample_rate == 48000);
    EXPECT(tags.channels == 2);
    EXPECT(tags.duration_ms == 5000);               // granule minus the pre-skip
}

TEST(tags_mp4) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "mp4.m4a"));
    EXPECT_STR(tags.title, "Bleu nuit");
    EXPECT_STR(tags.artist, "Sylvie Aumont");
    EXPECT_STR(tags.album, "Horizons");
    EXPECT_STR(tags.album_artist, "Sylvie Aumont");
    EXPECT_STR(tags.genre, "Electronic");
    EXPECT(tags.track_no == 3);
    EXPECT(tags.disc_no == 1);
    EXPECT(tags.year == 2012);
    EXPECT(tags.duration_ms == 185500);             // mvhd, timescale 1000
    EXPECT(tags.sample_rate == 44100);
    EXPECT(tags.channels == 2);
    EXPECT(tags.codec == LibCodec_M4A);
    EXPECT(tags.replaygain_track_db == -1856);      // the "----" freeform item
    EXPECT(tags.cover_size == 512 && tags.cover_hash != 0);
}

TEST(tags_mp4_moov_last) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "mp4_moov_last.m4a"));
    EXPECT_STR(tags.title, "Fin de bande");
    EXPECT_STR(tags.album, "Rushes");
    EXPECT(tags.track_no == 9);
    EXPECT(tags.disc_no == 2);
    EXPECT(tags.duration_ms == 241000);
}

TEST(tags_wav) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "wav.wav"));
    EXPECT_STR(tags.title, "Prise 3");
    EXPECT_STR(tags.artist, "Quatuor Lyre");
    EXPECT_STR(tags.album, "Sessions");
    EXPECT_STR(tags.genre, "Classical");
    EXPECT(tags.track_no == 6);
    EXPECT(tags.year == 2004);
    EXPECT(tags.codec == LibCodec_WAV);
    EXPECT(tags.sample_rate == 44100);
    EXPECT(tags.channels == 2);
    EXPECT(tags.duration_ms == 2000);
}

TEST(tags_aiff) {
    Tags tags;
    EXPECT(test_tags_read(arena, &tags, "aiff.aif"));
    EXPECT_STR(tags.title, "Boucle courte");
    EXPECT_STR(tags.artist, "Pierre Vidal");
    EXPECT(tags.codec == LibCodec_AIFF);
    EXPECT(tags.sample_rate == 44100);
    EXPECT(tags.channels == 2);
    EXPECT(tags.duration_ms == 3000);
}

// --- the broken ones -------------------------------------------------------
// None of these may crash, none may return a half filled struct: whatever the
// parsers make of them, the fallbacks still give the row a title.
static const char *test_tags_broken[] = {
    "broken_truncated.mp3", "broken_huge_size.mp3", "broken_frame_size.mp3",
    "broken_flac.flac",     "broken_ogg.ogg",       "broken_mp4.m4a",
    "broken_wav.wav",       "broken_mp4_loop.m4a",  "broken_ape.mp3",
    "empty.mp3",            "tiny.mp3",
};

TEST(tags_broken_fail_cleanly) {
    for (u64 i = 0; i < ArrayCount(test_tags_broken); i += 1) {
        Tags tags;
        test_tags_read(arena, &tags, test_tags_broken[i]);
        EXPECT(tags.title.size != 0);               // the file name, at worst
        EXPECT(tags.text_size <= TAGS_TEXT_CAPACITY);
        EXPECT(tags.title.size <= TAGS_FIELD_MAX);
        EXPECT(tags.duration_ms < 24u * 3600u * 1000u);
        EXPECT(tags.channels <= 8);
        EXPECT(tags.sample_rate <= 768000);
    }
}

TEST(tags_text_is_canonical) {
    // Invalid UTF-8 in, replacement characters out - never the raw bytes.
    u8 buffer[64];
    u8 raw[] = {'a', 0xC3, 0x28, 'b'};
    String8 clean = tags_utf8_clean(str8(raw, sizeof(raw)), buffer, sizeof(buffer));
    EXPECT(clean.size == 6);                        // 'a' + U+FFFD + '(' + 'b'
    EXPECT(clean.str[1] == 0xEF && clean.str[2] == 0xBF && clean.str[3] == 0xBD);

    u8 latin[] = {'c', 'a', 'f', 0xE9};
    String8 utf8 = tags_latin1_to_utf8(str8(latin, sizeof(latin)), buffer, sizeof(buffer));
    EXPECT(str8_eq(utf8, str8_lit("caf\xC3\xA9")));

    EXPECT(tags_parse_gain_db(str8_lit("-7.25 dB")) == -1856);
    EXPECT(tags_parse_gain_db(str8_lit("+0.00 dB")) == 0);
    EXPECT(tags_parse_gain_db(str8_lit("junk")) == 0);
    EXPECT(str8_eq(tags_genre_by_index(0), str8_lit("Blues")));
    EXPECT(str8_eq(tags_genre_by_index(125), str8_lit("Dance Hall")));
    EXPECT(tags_genre_by_index(126).size == 0);
    EXPECT(tags_genre_by_index(9999).size == 0);
}

// --- the fuzz --------------------------------------------------------------
// 10 000 mutations of every vector. The point is not what the parser returns -
// it is that ASan sees no read outside the buffer, and that the output stays
// inside its own bounds whatever the bytes said.
#define TEST_TAGS_FUZZ 10000

static const char *test_tags_all[] = {
    "id3v23_utf16.mp3", "id3v24_unsync.mp3", "id3v22.mp3", "id3v1_only.mp3",
    "mpeg_vbri.mp3", "ape_tail.mp3", "flac.flac", "ogg_vorbis.ogg", "opus.opus",
    "mp4.m4a", "mp4_moov_last.m4a", "wav.wav", "aiff.aif",
    "broken_truncated.mp3", "broken_huge_size.mp3", "broken_frame_size.mp3",
    "broken_flac.flac", "broken_ogg.ogg", "broken_mp4.m4a", "broken_wav.wav",
    "broken_mp4_loop.m4a", "broken_ape.mp3",
};

TEST(tags_fuzz_mutations) {
    u64 parsed = 0;
    for (u64 f = 0; f < ArrayCount(test_tags_all); f += 1) {
        ArenaTemp temp = arena_temp_begin(arena);
        TestTagFile original = test_tags_load(temp.arena, test_tags_all[f]);
        if (original.bytes.size == 0) { EXPECT(0); arena_temp_end(temp); continue; }
        // The mutated copy is its own allocation: ASan puts a red zone around
        // it, so one byte past the end is a crash and not a lucky read.
        u8 *copy = push_array(temp.arena, u8, original.bytes.size);
        u64 seed = 0x9E3779B97F4A7C15ull ^ f;
        for (u64 i = 0; i < TEST_TAGS_FUZZ; i += 1) {
            mem_copy(copy, original.bytes.str, original.bytes.size);
            u64 mutations = 1 + (hash64_mix(seed++) % 4);
            for (u64 m = 0; m < mutations; m += 1) {
                u64 at = hash64_mix(seed++) % original.bytes.size;
                copy[at] = (u8)(hash64_mix(seed++) & 0xFF);
            }
            TagsFile file;
            StructZero(&file);
            file.head = str8(copy, original.bytes.size);
            file.size = original.bytes.size;

            Tags tags;
            tags_init(&tags);
            if (tags_parse(&tags, &file)) { parsed += 1; }
            // Whatever it read, the output stays canonical.
            AssertAlways(tags.text_size <= TAGS_TEXT_CAPACITY);
            AssertAlways(tags.title.size <= TAGS_FIELD_MAX);
            AssertAlways(tags.cover_hashed <= original.bytes.size);
            AssertAlways(tags.cover_offset <= original.bytes.size);
        }
        arena_temp_end(temp);
    }
    // A mutation is one byte in a few thousand: most files still parse, which
    // is what makes this fuzz reach the deep paths instead of the first check.
    EXPECT(parsed > (u64)ArrayCount(test_tags_all) * TEST_TAGS_FUZZ / 2);
}

static void test_tags_run_all(void) {
    test_report("tags\n");
    RUN(tags_id3v23_utf16);
    RUN(tags_id3v24_unsync_utf8);
    RUN(tags_id3v22);
    RUN(tags_id3v1_and_cbr);
    RUN(tags_mpeg_vbri);
    RUN(tags_ape_tail);
    RUN(tags_flac);
    RUN(tags_ogg_vorbis);
    RUN(tags_opus);
    RUN(tags_mp4);
    RUN(tags_mp4_moov_last);
    RUN(tags_wav);
    RUN(tags_aiff);
    RUN(tags_broken_fail_cleanly);
    RUN(tags_text_is_canonical);
    RUN(tags_fuzz_mutations);
}
