// main.c - unity build: the single translation unit holding all of our code (ADR-002).
#include "base/base.h"
#include "base/base_arena.h"
#include "base/base_string.h"
#include "base/base_math.h"
#include "base/base_hash.h"
#include "platform/platform.h"
#include "base/base_jobs.h"
#include "core/library/lib_model.h"
#include "core/library/lib_events.h"
#include "core/library/lib_scan.h"
#include "ui/gl_loader.h"
#include "ui/r_core.h"
#include "ui/r_backend.h"
#include "ui/r_atlas.h"
#include "ui/r_raster.h"
#include "ui/r_icons.h"
#include "ui/ui_font.h"
#include "ui/ui_text.h"
#include "ui/ui_theme.h"
#include "ui/ui_core.h"
#include "ui/ui_widgets.h"
#include "ui/ui_debug_overlay.h"

#if BUILD_NO_CRT
#include "base/base_crt_stubs.c"
#endif

#include "base/base_arena.c"
#include "base/base_string.c"
#include "base/base_math.c"
#include "base/base_hash.c"
#include "base/base_jobs.c"

#include "platform/win32/win32_platform.c"
#include "platform/win32/win32_file.c"
#include "platform/win32/win32_dialog.c"
#include "platform/win32/win32_thread.c"
#include "platform/win32/win32_window.c"
#include "platform/win32/win32_gl.c"
#include "platform/win32/win32_font_dwrite.c"

#include "core/library/lib_model.c"
#include "core/library/lib_scan.c"

#include "ui/gl_loader.c"
#include "ui/r_atlas.c"
#include "ui/r_raster.c"
#include "ui/r_icons.c"
#include "ui/r_core.c"
#include "ui/r_gl.c"
#include "ui/ui_font.c"
#include "ui/ui_text.c"
#include "ui/ui_theme.c"
#include "ui/ui_core.c"
#include "ui/ui_widgets.c"
#include "ui/ui_debug_overlay.c"

#include "app/app.c"
